import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const systemFont = localFont({ 
  src: '../public/fonts/inter/Inter-VariableFont_opsz,wght.ttf',
  variable: "--system-font",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${systemFont.variable} h-full antialiased`}
    >
        dashboard
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
